[package]
name = "wacky"
version = "0.1.0"
authors = ["Lari Nurkka <lari@f-m.fm>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argparse = "0.2.2"
image = "0.22.1"
glob = "0.3.0"
